### ISSUE TITLE
Question about data import export etc.

### ISSUE THREAD

**Issue by hetszunyukapanyanyimonyok** [polymorphicshade/Tubular#1]
Hello @poymorphicshade!

I am glad to see your new project.
I have read the last discussion about the Tublar project and I read that there will be special options like filter keywords, channels etc.

Will you keep this Tublar specific data separate from newpipe data or will it be in the same file? 
Will the new backed up files incompatible with other New pipe versions?
What is the plan?

Thank you for your time in this project!

**Comment by polymorphicshade** [comment]
Old and new stuff will go in the same database file.

NewPipe and Tubular are separate apps, so anything in Tubular won't mess with anything in NewPipe.

**Comment by hetszunyukapanyanyimonyok** [comment]
Sorry maybe I was not clear enough.
I do understand what you mean.
In this cease if I export Tublar database(with filter data etc) can I use it in New pipe or will it cause an issue?

**Comment by polymorphicshade** [comment]
Oh! I'm not sure... as long as I don't touch the existing NewPipe tables then I think it will work.

**Comment by Tokopah** [comment]
Ive been unable to import my data from the previous fork of newpipe sponsorblock.  Causes the app to crash.

**Comment by hetszunyukapanyanyimonyok** [comment]
@Tokopah @polymorphicshade Wrote in an other forum that there is a bug and will fix it in next release.

**Comment by paulverbeke** [comment]
Hi, I'm trying to import my Tubular 0.26.1_r3 export to NewPipe 0.26.1 and Newpipe crashes. "A migration from 8 to 7 was required but not found"

**Comment by polymorphicshade** [comment]
> Hi @polymorphicshade, I'm trying to import my Tubular 0.26.1_r3 export to NewPipe 0.26.1 and Newpipe crashes. "A migration from 8 to 7 was required but not found". Looks like the backup format was altered. Do you think it would possible to have an cross compatible backup ? Thanks a lot

Tubular's database schema is different compared to vanilla NewPipe's database schema, so importing won't work.

Feel free to make a new feature request about exporting the database for backwards-compatibility, but I doubt I'll get to it any time soon.

**Comment by paulverbeke** [comment]
all right, thanks for the update. It would have been nice to know that I can't go back to vanilla before I used Tubular so extensively. Maybe we could add a warning in the readme for the next people that want to go back ?

**Comment by polymorphicshade** [comment]
> all right, thanks for the update. It would have been nice to know that I can't go back to vanilla before I used Tubular so extensively. Maybe we could add a warning in the readme for the next people that want to go back ?

Good idea!

Also, you can probably fix the database yourself by using any standard sqlite editor.

**Comment by paulverbeke** [comment]
thanks good to know

**Comment by paulverbeke** [comment]
looks harder than originally thought.
I dropped sponsorblock_whitelist table, then changed the pragma user version to 7
but still got an error during import "looks like you've changed schema but forgot to update the version number". I don't like beeing blocked on Tubular

**Comment by paulverbeke** [comment]
can confirm that with v0.27 you can now export Tubular database and import it to Newpipe perfectly !
Thanks @polymorphicshade
