### ISSUE TITLE
Please add the "Fix crash in MediaSessionPlayerUi while destroying player" Patch

### ISSUE THREAD

**Issue by TheBSODAndWSODFan** [polymorphicshade/Tubular#116]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for Tubular itself and that requests for adding a new service need to be made in [vanilla NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

this fixes crashes when the video buffering then crashed into guru meditation screen
https://github.com/TeamNewPipe/NewPipe/issues/11029

### Why do you want this feature?

just want to same as newpipe 0.27.1 release notes

### Why ist the feature relevant to this fork?

Nothing, since it already merged the pull request in the master branch of newpipe, but not in dev branch of newpipe

### Additional information

this is related pull request
https://github.com/TeamNewPipe/NewPipe/pull/11261

**Comment by HairyMilkshakes** [comment]
Can confirm I am running into this issue as well, thought it was just a bad connection but video will crash around 1 min in.

**Comment by TheBSODAndWSODFan** [comment]
i will close this issue since in newpipe dev branch already merged
