### ISSUE TITLE
The screen dims when the video is fullscreen

### ISSUE THREAD

**Issue by Stropdas** [polymorphicshade/Tubular#12]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Tubular 0.26.1_r2

### Steps to reproduce the bug

1. Start a video
2. Set it fullscreen

### Expected behavior

The video goes fullscreen and the brightness is controllable just as NewPipe 0.26.1 does without problems

### Actual behavior

The brightness dimms so it's hardly watchable in daylight 

### Affected Android/Custom ROM version

GrapheneOS 14

### Affected device model

Google Pixel 8 Pro

### Additional information

It works on the NewPipe-app without a problem.

**Comment by RoonMoonlight** [comment]
Try turning off the swipe to control from Tubular settings

**Comment by polymorphicshade** [comment]
@Stropdas are you still able to reproduce this?

**Comment by Stropdas** [comment]
I am on 0.26.1_r3 now. It works without a problem now. Haven't used the app much in the meantime. Will do that more often. Thanks!
