### ISSUE TITLE
Upstream 27.2

### ISSUE THREAD

**Issue by asandikci** [polymorphicshade/Tubular#128]
This is a friendly reminder, upstream Newpipe released 27.2 version for new 403 error fix. We would be thankful if you could merge in your spare time.

Thanks in advance !

---

### Summary for Users
- Debug apk made by Glich440: [Tubular-fix.apk.zip](https://github.com/user-attachments/files/16390264/Tubular-fix.apk.zip) (where is the source code 🤔)
- Another Release by me: [MaintainTeam/LastPipeBender.apk](https://github.com/MaintainTeam/LastPipeBender/releases/download/v0.27.2/lastpipebender_v0.27.2.apk) (different app name + signing key)
- Tubular PR for fix: https://github.com/polymorphicshade/Tubular/pull/129

**Comment by Glich440** [comment]
I made a quick debug build with the changes from upstream, you can use it in the meantime 
[Tubular-fix.apk.zip](https://github.com/user-attachments/files/16390264/Tubular-fix.apk.zip)

**Comment by profucius** [comment]
> I made a quick debug build with the changes from upstream, you can use it in the meantime [Tubular-fix.apk.zip](https://github.com/user-attachments/files/16390264/Tubular-fix.apk.zip)

This does work. Unfortunately because its a new package name, it's appdata is separate, which means that it forks my viewing history etc. I know its just for debugging purposes, but I rely on keeping my watch history. I suppose I'll have to wait for the official, but thank you anyway.

**Comment by njanbobby** [comment]
> > I made a quick debug build with the changes from upstream, you can use it in the meantime [Tubular-fix.apk.zip](https://github.com/user-attachments/files/16390264/Tubular-fix.apk.zip)
> 
> This does work. Unfortunately because its a new package name, it's appdata is separate, which means that it forks my viewing history etc. I know its just for debugging purposes, but I rely on keeping my watch history. I suppose I'll have to wait for the official, but thank you anyway.

You could export database from the Tubular app, and restore it in the temp app. Atleast that's how I keep my history and subscriptions

**Comment by tuxayo** [comment]
@Glich440  did you need to solve conflicts in the code to make that build?

If for hotfixes, conflicts rarely happen, the Tubular project could have a CI/CD that when a new tag is pushed upstream, it would rebase Tubular and build and publish a debug APK automatically. (assuming a volunteer has time to setup such an automated build)

**Comment by Glich440** [comment]
a few small ones

**Comment by asandikci** [comment]
Hello again. I'm a daily YouTube (NewPipe/Tubular) user. So I want to build NewPipe + Tubular with my own in a separate repo. if you're impatient like me and want to access the working application now you can visit [MaintainTeam/LastPipeBender](https://github.com/MaintainTeam/LastPipeBender/releases). This is a Release build (not debug), signed with my keys and includes both tubular/newpipe latest master branches (plus a mini rebranding). Also build is generated with Github Actions CI/CD 😊

Also a PR for merging latest NewPipe hotfix is on the way (see https://github.com/polymorphicshade/Tubular/pull/129). You can wait for it to be merged

**Comment by xray** [comment]
@asandikci [We'll see](https://github.com/polymorphicshade/TubularExtractor/pull/16#issuecomment-2227100460), I would like it if we could all just get behind Tubular. It does what y'all want it to, y'all are just unsatisfied with the release pace. Which is understandable when it's something as commonly used as YT. I did my best with my pull requests to follow the same pattern as @polymorphicshade when merging with remote but I'm not 100% sure if it's to spec.

**Comment by MuerteRoja** [comment]
> Hello again. I'm a daily YouTube (NewPipe/Tubular) user. So I want to build NewPipe + Tubular with my own in a separate repo. if you're impatient like me and want to access the working application now you can visit [MaintainTeam/LastPipeBender](https://github.com/MaintainTeam/LastPipeBender/releases). This is a Release build (not debug), signed with my keys and includes both tubular/newpipe latest master branches (plus a mini rebranding). Also build is generated with Github Actions CI/CD 😊
> 
> Also a PR for merging latest NewPipe hotfix is on the way (see #129). You can wait for it to be merged

May I ask what is the difference between your project and Newpipe and Tubular? I have seen the link you have attached and from my point of view, as I see it, it is the Tubular application only with a different name, hence the nature of my question, what features differentiate your application from Tubular and Newpipe?

**Comment by asandikci** [comment]
> @asandikci [We'll see](https://github.com/polymorphicshade/TubularExtractor/pull/16#issuecomment-2227100460), I would like it if we could all just get behind Tubular. It does what y'all want it to, y'all are just unsatisfied with the release pace. Which is understandable when it's something as commonly used as YT. I did my best with my pull requests to follow the same pattern as @polymorphicshade when merging with remote but I'm not 100% sure if it's to spec.

You did the best you could. We are grateful for the improvements and fixes made by the NewPipe Team and polymorphicshade. The only problem for some people here is, as you said, the release pace.


I realize that this is an open source hobby project and he is not responsible for updating it all the time. I can only wish that, but I can't force it. So I exercised my natural right to fork and merge (and the reason I changed the name was to avoid confusion of signatures). Of course, I would like not to deal with all this and continue under this (Tubular) repo.

**Comment by asandikci** [comment]
> > Hello again. I'm a daily YouTube (NewPipe/Tubular) user. So I want to build NewPipe + Tubular with my own in a separate repo. if you're impatient like me and want to access the working application now you can visit [MaintainTeam/LastPipeBender](https://github.com/MaintainTeam/LastPipeBender/releases). This is a Release build (not debug), signed with my keys and includes both tubular/newpipe latest master branches (plus a mini rebranding). Also build is generated with Github Actions CI/CD 😊
> > Also a PR for merging latest NewPipe hotfix is on the way (see #129). You can wait for it to be merged
> 
> May I ask what is the difference between your project and Newpipe and Tubular? I have seen the link you have attached and from my point of view, as I see it, it is the Tubular application only with a different name, hence the nature of my question, what features differentiate your application from Tubular and Newpipe?

@MuerteRoja If applicationID's same and signing keys are different, you could not update app and probably get "app could not be installed" error. Thats why I changed applicationID/Application Name. I also have an idea to merge several newpipe forks for the future. I thought it was a good name for it. The rest of all source code is same with NewPipe/Tubular. I didn't add any other line/feature and won't add any in near future too.

**Comment by MuerteRoja** [comment]
> > > Hello again. I'm a daily YouTube (NewPipe/Tubular) user. So I want to build NewPipe + Tubular with my own in a separate repo. if you're impatient like me and want to access the working application now you can visit [MaintainTeam/LastPipeBender](https://github.com/MaintainTeam/LastPipeBender/releases). This is a Release build (not debug), signed with my keys and includes both tubular/newpipe latest master branches (plus a mini rebranding). Also build is generated with Github Actions CI/CD 😊
> > > Also a PR for merging latest NewPipe hotfix is on the way (see #129). You can wait for it to be merged
> > 
> > 
> > May I ask what is the difference between your project and Newpipe and Tubular? I have seen the link you have attached and from my point of view, as I see it, it is the Tubular application only with a different name, hence the nature of my question, what features differentiate your application from Tubular and Newpipe?
> 
> @MuerteRoja If applicationID's same and signing keys are different, you could not update app and probably get "app could not be installed" error. Thats why I changed applicationID/Application Name. I also have an idea to merge several newpipe forks for the future. I thought it was a good name for it. The rest of all source code is same with NewPipe/Tubular. I didn't add any other line/feature and won't add any in near future too.

I understand, for now I will start using your application to see how it goes, I have imported my Tubular playlist to LastPipeBender without problems, it would be interesting if you could also upload the application to application stores such as F-Droid and Droid-ify so that more people have the possibility to try it.

**Comment by MuerteRoja** [comment]
> > > Hello again. I'm a daily YouTube (NewPipe/Tubular) user. So I want to build NewPipe + Tubular with my own in a separate repo. if you're impatient like me and want to access the working application now you can visit [MaintainTeam/LastPipeBender](https://github.com/MaintainTeam/LastPipeBender/releases). This is a Release build (not debug), signed with my keys and includes both tubular/newpipe latest master branches (plus a mini rebranding). Also build is generated with Github Actions CI/CD 😊
> > > Also a PR for merging latest NewPipe hotfix is on the way (see #129). You can wait for it to be merged
> > 
> > 
> > May I ask what is the difference between your project and Newpipe and Tubular? I have seen the link you have attached and from my point of view, as I see it, it is the Tubular application only with a different name, hence the nature of my question, what features differentiate your application from Tubular and Newpipe?
> 
> @MuerteRoja If applicationID's same and signing keys are different, you could not update app and probably get "app could not be installed" error. Thats why I changed applicationID/Application Name. I also have an idea to merge several newpipe forks for the future. I thought it was a good name for it. The rest of all source code is same with NewPipe/Tubular. I didn't add any other line/feature and won't add any in near future too.

By the way, I'm giving you this warning in good faith, because I have a lot of respect for people like you who want to start their own projects. If your project succeeds, start getting mentally prepared for the typical people who won't stop asking you questions like: "The latest Newpipe update come out, When are you going to update the LastPipeBender app?" This always happens with all projects, and that's why there are developers who can't help but answer in a rude and unfriendly way. Because on a mental/psychological level, this type of question wears you down.

PS: I apologize for my poor English, I'm using a translator to communicate, but well, regardless of how "badly" I've spoken, I guess you've understood the general idea of ​​the context.

**Comment by njanbobby** [comment]
> > > > Hello again. I'm a daily YouTube (NewPipe/Tubular) user. So I want to build NewPipe + Tubular with my own in a separate repo. if you're impatient like me and want to access the working application now you can visit [MaintainTeam/LastPipeBender](https://github.com/MaintainTeam/LastPipeBender/releases). This is a Release build (not debug), signed with my keys and includes both tubular/newpipe latest master branches (plus a mini rebranding). Also build is generated with Github Actions CI/CD 😊
> > > > Also a PR for merging latest NewPipe hotfix is on the way (see #129). You can wait for it to be merged
> > > 
> > > 
> > > May I ask what is the difference between your project and Newpipe and Tubular? I have seen the link you have attached and from my point of view, as I see it, it is the Tubular application only with a different name, hence the nature of my question, what features differentiate your application from Tubular and Newpipe?
> > 
> > 
> > @MuerteRoja If applicationID's same and signing keys are different, you could not update app and probably get "app could not be installed" error. Thats why I changed applicationID/Application Name. I also have an idea to merge several newpipe forks for the future. I thought it was a good name for it. The rest of all source code is same with NewPipe/Tubular. I didn't add any other line/feature and won't add any in near future too.
> 
> By the way, I'm giving you this warning in good faith, because I have a lot of respect for people like you who want to start their own projects. If your project succeeds, start getting mentally prepared for the typical people who won't stop asking you questions like: "The latest Newpipe update come out, When are you going to update the LastPipeBender app?" This always happens with all projects, and that's why there are developers who can't help but answer in a rude and unfriendly way. Because on a mental/psychological level, this type of question wears you down.
> 
> PS: I apologize for my poor English, I'm using a translator to communicate, but well, regardless of how "badly" I've spoken, I guess you've understood the general idea of ​​the context.

See, if this release by newpipe was some ui change, or addition of features, people wouldn't have cared waiting for the application being updated. But for the last two releases 0.27.1 and 0.27.2, the application that you can use to watch videos, was not able to do that. Since the core functionality is broken, people (including me) don't have the patience to wait for long.
I certainly appreciate polymorphicshade for all his work that he had done, and is currently doing, but when the core functionality is broken, it is understandable that people get impatient.

**Comment by polymorphicshade** [comment]
Thank you @asandikci. I'm aware of when NewPipe releases a new version.

As usual, I'll get to it when I have a chunk of free time to dedicate.

**Comment by HueponiK** [comment]
If you decide to make a fork, you are either got what it takes to maintain it, and you commit to it, or your fork dies or get forked itself.

It's fine, that's what's great about it.
No one is owed anything.

Mainteners don't owe us anything, and no one owns maintainers not making a fork.

Apple is a great choice for people who wants one strong hand holding everyone and dictating how you should use your device/software.

I'd rather have 3 apks installed than not being able to use it at all or enjoying ads and tracking

**Comment by lameventanas** [comment]
> Since the core functionality is broken, people (including me) don't have the patience to wait for long.

Yes, it's a bit irritating that the core functionality is broken. But what was worse was the response with memes and whatnot instead of just communicating like normal people. Not everyone has the same sense of humor, many people didn't even understand what was going on, and others just thought it was stupid or immature.
This time it was totally different.

**Comment by kaoneko** [comment]
I think @polymorphicshade should use any time they spend on Tubular to solve the known issue of:

> every time a sponsor is skipped manually using the "Skip" button, an orphan is sacrificed

This is far more important. Actually, not publishing a build with the upstream fix is the _humane_ thing to do, since as long as y'all can't watch videos with Tubular, the orphans are safe. 

I stand with the orphans! ✌🏻

**Comment by Juan-de-Costa-Rica** [comment]
> > I made a quick debug build with the changes from upstream, you can use it in the meantime [Tubular-fix.apk.zip](https://github.com/user-attachments/files/16390264/Tubular-fix.apk.zip)
> 
> This does work. Unfortunately because its a new package name, it's appdata is separate, which means that it forks my viewing history etc. I know its just for debugging purposes, but I rely on keeping my watch history. I suppose I'll have to wait for the official, but thank you anyway.

What I've been done is downloaded the new version of newpipe which is working with YouTube..  then I can check my subscriptions on tubular and if I want to watch something I just hit the share button and share the link from tubular to newpipe. 
Not ideal, but easy enough until tubular updates!

**Comment by Sohail-XD** [comment]
No update on izzydroid yet :(

**Comment by asandikci** [comment]
@Sohail-XD IzzyOnDroid repo is updating with an interval (24H I guess). Just wait a bit more (probably repo will be update in 3-4 hour)
`Last updated: 2024-07-27 17:43 UTC`

**Comment by anh0516** [comment]
It's up!
