### ISSUE TITLE
Use dearrow video titles

### ISSUE THREAD

**Issue by je-vv** [polymorphicshade/Tubular#13]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Besides sponsorblock, a very good companion from the same author is dearrow video titles to prevent click baits.  This most probably won't be implemented by newpipe since they decided not to even use sponsorblock.

### Why do you want this feature?

To get a better tubular/newpipe videos traversing experience, looking at what originally the video is intended to, rather than looking at click baits redrawings.

### Additional information

See [dearrow](https://dearrow.ajay.app) and [dearrow about](https://dearrow.ajay.app/about)

Thanks a lot !

**Comment by polymorphicshade** [comment]
#4
