### ISSUE TITLE
Comments not showing up

### ISSUE THREAD

**Issue by eddieofny** [polymorphicshade/Tubular#16]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1_r2

### Steps to reproduce the bug

Comments will occasionally be missing on videos. If I close the video and reopen it, the comments will load properly.
![Screenshot_2024-02-02-08-53-08_1](https://github.com/polymorphicshade/Tubular/assets/98845254/71e11d4d-ea95-4044-b565-888772411a3a)

### Affected Android/Custom ROM version

Android 7.0

### Affected device model

LG K20 Plus

**Comment by polymorphicshade** [comment]
@eddieofny 
Have you seen this on vanilla NewPipe? I don't think this issue is specific to Tubular.
