### ISSUE TITLE
Arithmetic overflow on view counter

### ISSUE THREAD

**Issue by Teskann** [polymorphicshade/Tubular#17]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1_r2

### Steps to reproduce the bug

Open any video with more than 2.15B views, such as [this one](https://www.youtube.com/watch?v=2Vv-BfVoq4g)

### Expected behavior

The number of likes is displayed as expected (in the case of the video above about 3.660B views)

### Actual behavior

You might see a negative value for the views, in the case of the video above, -634M

### Additional information

New Pipe 0.26.1 is not affected by this bug, this is why I report it here.

Probably using a 64 bits integer would be more suitable for the views counter.

**Comment by mikooomich** [comment]
Yep, can reproduce. This however, is fixed in NewPipe's current dev branch (somewhere).
