### ISSUE TITLE
Error 502 / Error 409 when submitting a sponsored segment

### ISSUE THREAD

**Issue by Monoxide8969** [polymorphicshade/Tubular#18]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1_r2

### Steps to reproduce the bug

Submit a sponsored segment

### Expected behavior

The submission is completed successfully

### Actual behavior

The app returns "Error 502". I kept trying, and I eventually got " Error 409"

### Screenshots/Screen recordings

<img alt="Screen" src="https://github.com/polymorphicshade/Tubular/assets/108904135/3b33d5f1-5172-4e62-abeb-3d2ce7c4da3f" width=445 />

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung A22 5G

**Comment by ajayyy** [comment]
This is a server problem. The 409 means your submission worked, the request just timed out and completed in the background slowly

**Comment by Monoxide8969** [comment]
My bad then. Still, it would be nice to add an additional line to the error to explain that it's server-side and it's not the user's nor the app's fault (to avoid similar submissions in the future)

**Comment by polymorphicshade** [comment]
@smed79 no problem!
I actually completely forgot about being able to set your own user name. Go ahead and make a feature request for it 😊
