### ISSUE TITLE
Any plans on porting this app for Linux ?

### ISSUE THREAD

**Issue by NotMainstream** [polymorphicshade/Tubular#20]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Any plans on porting this app for Linux ?
.

### Why do you want this feature?

I'm asking this because I use both mobile and desktop for YT and it would be awesome if we can sync in between the mobile with PC so we don't have to use a Google account on desktop and continue watching the same channels and playlists.
Thanks.

**Comment by tuxayo** [comment]
(I'm just a passer by) Very likely so much stuff would need to be recoded that it wouldn't make sense.

The FreeTube client also exists:
https://freetubeapp.io/
https://github.com/FreeTubeApp/FreeTube

**Comment by Fauli1221** [comment]
You can already have this on Linux using
https://waydro.id/

**Comment by OrdinaryCloverOC** [comment]
https://gitlab.com/android_translation_layer/android_translation_layer/-/issues/46#note_2442153293 there's an android translation layer and i was wondering if they could get permission to put tubular on flatpak? (sorry if i should've opened a new issue instead)

**Comment by os-guy** [comment]
Yea, considering ATL for running it on Linux would be much easier.
