### ISSUE TITLE
Download entire playlist

### ISSUE THREAD

**Issue by Staubsaugerbeutel** [polymorphicshade/Tubular#23]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add a "download all" button next to Background / Play All / Popup in the playlist view.
Set video/audio & quality setting once, then save all the videos with the default filename.
Not sure if you guys are able to implement this but it doesn't seem too sophisticated.

### Why do you want this feature?

This would make the app a strong YT download tool.
Would be generally cool to have this to download music playlists for offline listening.

**Comment by polymorphicshade** [comment]
Looks like vanilla NewPipe has an existing issue related to this kind of feature:
- https://github.com/TeamNewPipe/NewPipe/issues/5482

I'd rather wait for vanilla NewPipe to implement this to reduce the amount of potential conflicts my fork may have.
