### ISSUE TITLE
Playlist view sorting options

### ISSUE THREAD

**Issue by KraXen72** [polymorphicshade/Tubular#25]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Please add sorting options to the playlist view - Latest added, Oldest added, A-Z, Z-A, Latest release date, Oldest release date.

### Why do you want this feature?

Currently, the playlists are always sorted from oldest added to newest added. I have to scroll for a long time to get to the bottom of the playlist to see new videos.

**Comment by polymorphicshade** [comment]
Looks like vanilla NewPipe has existing issues related to this kind of feature:
- https://github.com/TeamNewPipe/NewPipe/issues/3263
- https://github.com/TeamNewPipe/NewPipe/issues/3037

I'd rather wait for vanilla NewPipe to implement this to reduce the amount of potential conflicts my fork may have.

**Comment by KraXen72** [comment]
Okay, I understand. However, the relevant issue is over 4 years old, and with newpipe focusing it's efforts on the gradual rewrite, i doubt it's likely we'll see a small QOL feature like this in the following few years. That's why I opened it here, in hopes of getting it sooner, but I understand if it increases the differences between vanilla and your fork.
