### ISSUE TITLE
Please take care to always increase versionCode

### ISSUE THREAD

**Issue by IzzySoft** [polymorphicshade/Tubular#28]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1.*

### Steps to reproduce the bug

n/a

### Expected behavior

Each release has its specific versionCode

### Actual behavior

all of them share versionCode 996

### Screenshots/Screen recordings

![image](https://github.com/polymorphicshade/Tubular/assets/6781438/3a720bf9-bf2b-4203-9b1b-7678f528f2d2)

### Logs

n/a

### Affected Android/Custom ROM version

n/a

### Affected device model

n/a

### Additional information

n/a

**Comment by polymorphicshade** [comment]
Ah I didn't know that actually mattered... I figured I'd keep the base version and code the same as vanilla NewPipe.
I'll start incrementing them independently 👍

**Comment by IzzySoft** [comment]
Thanks! For some background: `versionCode` is what Android uses internally to tell versions apart. So even if my updater will pull the `v0.26.1_r3` today and overwrite `v0.26.1_r2` with it (as the APK file name is `<packageName>_<versionCode>.apk` for the reason outlined). those who have `_r1` or `_r2` installed won't get it shown as update – because Android only looks at the `versionCode` and says: well, that's already installed, so no action needed.

`versionName` however is just for display and has no technical implications like that.

**Comment by IzzySoft** [comment]
@kubo6472 that would be a bit confusing to those already using the app, no? Tubular is [in my repo](https://apt.izzysoft.de/packages/org.polymorphicshade.tubular/) since January. And if you still keep sync with upstream NewPipe, aligning `versionName` (maybe introducing an additional digit if you release more frequent) would probably be the easiest way for folks to know what to compare it to.

> put this at 0.1.1 as the first version? Then use version name or something to track related newpipe base?

0.1.1 would be the `versionName`, btw :wink: That's the part visual to those using the app. And you cannot "start with a fresh `versionCode`" (which is the integer @polymorphicshade and I were talking about) as that would mean everybody using the app already would have to uninstall and reinstall, as Android would consider that a downgrade which it does not allow.

**Comment by IzzySoft** [comment]
Curiosity is good, many good things have been discovered that way :smile: So yeah, those are the two I was referring to. `versionCode` is what Android uses internally to tell versions apart, and `versionName` is what those using the app will see. While the latter has no real technical implications, good practice there is to use [semantic versioning](https://semver.org/), which seems to be applied here.
