### ISSUE TITLE
New videos notifications shows videos that are not new

### ISSUE THREAD

**Issue by stemy2** [polymorphicshade/Tubular#32]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

Subscribe to some channels.
Waut for the next update.

### Expected behavior

Notifies only when there are new videos.

### Actual behavior

I'm notified for videos that were already present in my feed.

### Affected Android/Custom ROM version

/e/OS 1.20

### Affected device model

fairphone 3

**Comment by polymorphicshade** [comment]
Does this happen with vanilla NewPipe?

**Comment by stemy2** [comment]
Yes, it does.

**Comment by polymorphicshade** [comment]
Ok, then this should be asked on their Github repo (I still need to edit the issue template on my repo...)
