### ISSUE TITLE
Nested comments

### ISSUE THREAD

**Issue by I3arana** [polymorphicshade/Tubular#33]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

May we have nested comments functionality?
 Possibly able to crossport it from pipepipe  -newpipe fork- source.

Gz and thanks for this fork, continuing the legacy of newpipe.
 Sponsorblock addition is grand. Very very useful.

### Why do you want this feature?

20/20 vision is nice,
And the author of pipepipe has done the heavy work.

### Additional information

No pictures of cats, I however have car pix.

Android 13 + 8849 Tank 2.

**Comment by polymorphicshade** [comment]
When this appears in an official release of NewPipe, this fork will have it too.

My old implementation is from some random fork, and the code has diverged from vanilla NewPipe, so I'd rather wait for upstream NewPipe to implement it.

**Comment by I3arana** [comment]
Thankyou for your detailed reply :)
