### ISSUE TITLE
Is this a replacement for Newpipe Sponsorblock?

### ISSUE THREAD

**Issue by terry9873** [polymorphicshade/Tubular#34]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

Sorry to open an issue, but i can't find ANY way to contact the devs or ask anyone about anything to do with Tubular, if someone could drop me a link, I'd appreciate it. 

I have used Newpipe Sponsorblock for a long while. I just noticed it's not listed in Fdroid any more (where I think I got it). I searched around and found something called "Tubular", first time I've heard of it. I notice it's version is 0.26, whereas my Newpipe Sponsorblock is v 0.25.1. I have a lot of bugs in it. 

Can I ask... 

1. Is this a replacement for Newpipe Sponsorblock? 
2. I had trouble with updates with Newpipe and the Sponsorblock version. If I install 'Tubular' in Droidify, will it update via Droidify as well? (In the past I had to download an APK to update Newpipe Sponsorblock. 
3. If I install it, will it pull its data (settings, subscriptions etc) from my old app, or do I need to set it up manually comparing the two apps?

Finally, sorry for opening this again, I have no clue how github works, and also thank you very much to the devs IF this is indeed a replacement for my beloved but now buggy Newpipe Sponsorblock! (If there's a page I can donate on, please link)

Thanks

**Comment by polymorphicshade** [comment]
@terry9873 yes this repo is intended to replace "NewPipe x SponsorBlock"

To find released APKs, see [here](https://github.com/polymorphicshade/Tubular/releases).

Also I won't be accepting donations, please donate to the vanilla NewPipe devs [here](https://newpipe.net/donate/).

**Comment by johnstonesnow** [comment]
> Yes, it is the continuation of NPSB I have never used drodify, but you could update it through Obtainium or NeoStore, for example. You can do a backup of NPSB and restore it on Tubular.
> 

thanks. Droidify is just a different front end for Fdroid. Never heard of Obtainium or Neostore. I might see if it's on Fdroid/Droidify and hope for updates there, otherwise will just grab apk direct. 

thanks again

**Comment by johnstonesnow** [comment]
I remember having trouble with original newpipe and getting updates. I think someone told me if I used the APK for it, it would download its own updates when new releases came out. Is that true of this? If I download this APK will it auto update, or is there a recommended procedure for getting updates?
thanks again, looking forward to trying it

**Comment by terry9873** [comment]
I remember having trouble with original newpipe and getting updates. I think someone told me if I used the APK for it, it would download its own updates when new releases came out. Is that true of this? If I download this APK will it auto update, or is there a recommended procedure for getting updates?
thanks again, looking forward to trying it

**Comment by johnstonesnow** [comment]
I'd rather an answer to my question as to whether this app will auto update. If it will, I don't need to undergo the stress of trying to learn how to use firstly github, secondly Obtainium.  I managed to install Obtainium for a look to see if I can use it. It wants a source URL for all apps. I don't have time (or knowledge) to do that, when all I need is this app and hopefully auto updating. If it doesn't auto update, I will look further at setting up this app in Obtainium.

**Comment by terry9873** [comment]
I'd rather an answer to my question as to whether this app will auto update. If it will, I don't need to undergo the stress of trying to learn how to use firstly github, secondly Obtainium. I managed to install Obtainium for a look to see if I can use it. It wants a source URL for all apps. I don't have time (or knowledge) to do that, when all I need is this app and hopefully auto updating. If it doesn't auto update, I will look further at setting up this app in Obtainium.

**Comment by terry9873** [comment]
Thanks. A good example in itself of why it feels like you either know how to use Github (because you're a dev), or you don't (because you're not!) 
Surely this is the 'releases' page? https://github.com/polymorphicshade/Tubular/releases
I get so confused, I basically dread opening any github page, often there's no alternative so I'm forced to appear as I did here!
So is Obtainium a totally new way to install apps (without play store), something like this:

1. Hear about an app
2. Find on github
3. Get releases page URL and put into Obtainium which installs and then tracks for updates

Is that about right?! 
Not sure if I should be doing that for all my other apps which are managed by Fdroid/Droidify. I know they aren't ideal, although Droidify is a bit 'safer' than Fdroid but I forget the reasons why!

I don''t have many apps really, very minimal setup on phone. I do have a few important ones like Signal though, which seems to auto update itself when needed

**Comment by terry9873** [comment]
PS - Important - I usually keep a few other devices up to date with NP/NPSB (and now it will be Tubular). A few elderly relatives and friends. They won't be able to set up Obtainium, so I'd still like to know if Tubular will update itself if I can get the apk installed direct?
