### ISSUE TITLE
Option to make timestamp seek player

### ISSUE THREAD

**Issue by scarf005** [polymorphicshade/Tubular#38]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

same as https://github.com/TeamNewPipe/NewPipe/issues/4241, to be able to have an option to click a timestamp in comment to seek the player instead of spawning a new player.

### Why do you want this feature?

same as the original newpipe issue, it'd be very convenient to be able to have matching behavior like youtube.

**Comment by polymorphicshade** [comment]
This will be in my fork when it's implemented and released in vanilla NewPipe.
