### ISSUE TITLE
Subscription Notifications Bug?

### ISSUE THREAD

**Issue by terry9873** [polymorphicshade/Tubular#39]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Latest

### Steps to reproduce the bug

Subscribe and turn on notifications

### Expected behavior

Expect notifications only when new content is published

### Actual behavior

I had this problem on NPSB. I've just moved to Tubular and same problem occurs, hoped it was due to NPSP being old now. I have say 10-20 subscriptions to YT channels in Tubular. For 4 or 5 of those, i have notifications turned on to alert me of newly published videos. But I keep getting notifications for old videos. For example today I got one for a video published back in December 2023?! 
This happens across all subscribed channels, and seems completely random. Thanks

**Comment by polymorphicshade** [comment]
Does this happen with vanilla NewPipe?
