### ISSUE TITLE
App crashes when playing long videos.

### ISSUE THREAD

**Issue by eddieofny** [polymorphicshade/Tubular#40]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1_r3

### Steps to reproduce the bug

Whenever I try to play long videos (anything longer than like, an hour) I get this error. I can get around it if I minimize the video while it's loading and then minimize the app when the video starts playing, but if I pause the video from the notification bar or lock screen, the app will crash.

### Expected behavior

The video plays like normal.

### Actual behavior

The app crashes during long videos.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.1_r3
* __OS:__ Linux lge/lv517_tmo_us/lv517:7.0/NRD90U/182891910c4ff:user/release-keys 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 7.0

### Affected device model

LG K20 Plus

**Comment by polymorphicshade** [comment]
Does this happen on vanilla NewPipe?
The crash log just shows that you ran out of memory.

**Comment by eddieofny** [comment]
Just downloaded NewPipe to check and no, NewPipe streams these long videos just fine. But NewPipe isnt receiving updates anymore anyways. I first noticed the problem on NewPipe x Sponsorblock, and it has carried over to Tubular. The problem also does not occur if I open a video in browser. It is specific to Tubular.

**Comment by polymorphicshade** [comment]
@eddieofny I cannot reproduce this issue, even on an emulator with only 1 GB of RAM.

Can you send me the video you were trying to play?

**Comment by eddieofny** [comment]
Sorry for getting back to you so late.

Here's the video: https://www.youtube.com/watch?v=V9cuZxdrvrk

Btw, I ended up using og Newpipe to watch this video, and while I was able to finish it, I began encountering similar issues. It took a little bit of time though, so when I first started the video there were no bugs, and the longer I watched, I started having issues. Not sure if that info helps or not.

**Comment by polymorphicshade** [comment]
@eddieofny v0.27.0 has been released.

Can you try to see if you get this issue again?

**Comment by eddieofny** [comment]
Sorry it took me so long to respond. I got a new phone last month and tubular has been working fine on it, even with long videos. But I just got around to testing it on the old phone today, and it is working perfectly there as well. Thank you
