### ISSUE TITLE
Choose audio bitrate within audio <play> mode.

### ISSUE THREAD

**Issue by I3arana** [polymorphicshade/Tubular#42]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for Tubular itself and that requests for adding a new service need to be made in [vanilla NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

We can choose video bitrate resolution, we can chose Audio only replay, We can choose video bitrate for downloads, We can choose Audio bitrate for downloads.
 With the highly useful new 32kb audio codec , could we chose the audio resolution for audio only playback?
 
 

### Why do you want this feature?

This will be infinitely useful to maintain smooth playback for poor reception areas, low bandwidth.

### Why ist the feature relevant to this fork?

First time ive thought of it or asked. 

### Additional information

I eat cats.

**Comment by polymorphicshade** [comment]
This is a great idea, but I have no plans to implement this.

This should be requested in the [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/issues) repo.

**Comment by I3arana** [comment]
thx for the direction, will do!
________________________________
