### ISSUE TITLE
Opening Videos results in longer loading times

### ISSUE THREAD

**Issue by g1t3m** [polymorphicshade/Tubular#51]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/Tubular/releases/latest).
- [X] I am *not* able to reproduce the bug with the *latest version* of [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1_r3

### Steps to reproduce the bug

1. Open Tubular app
2. Open several videos

### Expected behavior

Videos take little time to load before playing, and load almost instantly.

### Actual behavior

After opening a few videos (or at least one video), subsequent videos take much longer time to load, if they load at all.

### Screenshots/Recordings

![Screenshot_20240406-195047](https://github.com/polymorphicshade/Tubular/assets/58442774/2088d0fd-b3e4-450e-89a7-7091853cc5f3)
![Screenshot_20240406-195106](https://github.com/polymorphicshade/Tubular/assets/58442774/62fade1f-15fb-4ce1-b4c7-02ed1cb52153)

### Affected Android/Custom ROM version

GrapheneOS 14 (AP1A.240405.002)

### Affected device model

Pixel 8 Pro

### Additional information

I pasted two examples: one of a longer video:
https://www.youtube.com/watch?v=tjs-Ra5KxSk

and one of a shorter video: https://www.youtube.com/watch?v=EbB9zECDIx4

I downloaded and tested these out in Newpipe, PipePipe and even LibreTube, all of which loaded the videos immediately.

**Comment by AbsurdlySuspicious** [comment]
Probably due to sponsor.ajay.app getting up and down sporadically. Consider temporary disabling sponsorblock as a workaround.

**Comment by polymorphicshade** [comment]
@g1t3m can you verify that if you disable SponsorBlock, the videos load faster?

**Comment by g1t3m** [comment]
Hello @polymorphicshade, it seems the issue has resolved itself; videos are loading as fast as they did prior to submitting this ticket. I did disable Sponsorblock to see if that made any difference, and it seems it didn't make much difference.

**Comment by GreenArchiveForever** [comment]
> @g1t3m can you verify that if you disable SponsorBlock, the videos load faster?

i still face this issues even with stock setting on Turbulat 0.27.0 and in vanilla it's opened almost immediately currently
