### ISSUE TITLE
Should we have a proper CI in GitHub?

### ISSUE THREAD

**Issue by asandikci** [polymorphicshade/Tubular#52]
Could you please have CI (GitHub Actions) for building/publishing app instead of building it locally and uploading manually. This provides a better security for users. Thanks in advance

**Comment by TheKyber** [comment]
Trying to make it possible and open a PR but I am having this issue at the checkout step:
`Error: error: unable to create symlink app/src/main/res/layout-land/list_stream_card_item.xml: File name too long`

Can you please take a look at this so I can handle the rest.
https://github.com/TheKyber/Tubular/actions/runs/8737197493/job/23973640700

**Comment by licaon-kter** [comment]
Seeing the same locally :(

**Comment by polymorphicshade** [comment]
@asandikci @thekyber @licaon-kter - could one of you look at the dev branch so far and see the CI/Release workflows I added? I'm relatively new to Github Actions so let me know if I'm missing anything.

As for the symlink thing, I work and develop with Windows machines, and the symbolic link for list_stream_card_item.xml was breaking the build on my machine, so I just copied the contents of the linked file. I have no idea how this may effect Git's ability to checkout the source code... Nonetheless I tweaked the workflow scripts to manually checkout the source code and I don't have this symlink problem anymore.

**Comment by thekyber** [comment]
@polymorphicshade I see that you solved the checkout problem and I am going to copy some of your workflow to mine before opening a PR.  

The `ci.yml` file looks good for me because it is for testing purposes, so it build the debug apk and upload it as an artifact that can be found in the details of the workflow run.

Howerver, I don't understand why are you uploading the release apk in `release.yml` as an artifact also, I assume that you wanted to upload it to the releases right?

Well, there should be also a step where you create a new release before uploading the apk file to it, and I am happy to help you with that.

The workflow that i am trying to make can create the tag and the release automatically by extracting the versionName from `app/build.gradle`. I will be testing it and keep you updated if there is anything new.

Feel free to ask anything altghouh I consider myself a beginner in GitHub Actions.

**Comment by thekyber** [comment]
https://github.com/polymorphicshade/Tubular/commit/5b6b243bef9d259e54616dd716ba2b1e63b7aeac#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9

You can also remove this commit if you want, because I like to sign the apk in a different step.

**Comment by thekyber** [comment]
I opened a PR. #57

**Comment by polymorphicshade** [comment]
@thekyber my intention was to manually make releases (so I can put in whatever detail I want), and manually attach an APK generated by the Release workflow.

I wanted keep the creation of the release separate from the "release" build and sign stuff in the workflow.

Is this a bad idea?

**Comment by thekyber** [comment]
To publish the apk file yourself you will have to download the artifact, unzip it locally, and then reupload, is it really worth the trouble?

I also don't understand why do you want to create the release manually.

The only reason for you to do this is to write some release notes befora publishing everything, but this also can be automated when you keep the release notes in a sepeate file (I don't know how to do this but I will see what I can do about it).

**Comment by polymorphicshade** [comment]
@thekyber oh I like that a lot better. Good idea 👍

**Comment by thekyber** [comment]
@polymorphicshade 
From what I saw in some workflows, you need to make a file that you will keep the release notes in it, then it will be included when creating the release to it will get the notes from there, should I take a look on how to do this?

**Comment by thekyber** [comment]
@polymorphicshade
By the way, I rely on GitHub CLI to handle the release creation and upload, but if you find it a bit confusing you can use something simpler and clearer from GitHub Marketplace, like this one:

https://github.com/marketplace/actions/create-release

**Comment by polymorphicshade** [comment]
@thekyber if you're already in the middle of figuring this out, go for it. I have very little free time, so you will probably end up with a solution before I do.

**Comment by thekyber** [comment]
@polymorphicshade
I will tell you when the PR is ready to merge.

**Comment by thekyber** [comment]
@polymorphicshade 

I managed to do it and it was pretty easy, you just have to create `changelog.md` file (or any other name), you write what you want it to be in the latest release notes, and it will be included in your workflow, and you're done.

This is my test:
https://github.com/thekyber/Tubular/releases/latest

**Comment by licaon-kter** [comment]
I can't even clone
```
$ git clone https://github.com/polymorphicshade/Tubular
Cloning into 'Tubular'...
remote: Enumerating objects: 133030, done.
remote: Counting objects: 100% (3463/3463), done.
remote: Compressing objects: 100% (1150/1150), done.
remote: Total 133030 (delta 1755), reused 3379 (delta 1700), pack-reused 129567
Receiving objects: 100% (133030/133030), 113.12 MiB | 11.52 MiB/s, done.
Resolving deltas: 100% (80505/80505), done.
error: unable to create symlink app/src/main/res/layout-land/list_stream_card_item.xml: File name too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by thekyber** [comment]
> I can't even clone
> 
```
git clone --no-checkout https://github.com/polymorphicshade/Tubular
```

**Comment by licaon-kter** [comment]
```
$ git clone --no-checkout https://github.com/polymorphicshade/Tubular
Cloning into 'Tubular'...
remote: Enumerating objects: 133599, done.
remote: Counting objects: 100% (4032/4032), done.
remote: Compressing objects: 100% (1342/1342), done.
error: 4489 bytes of body are still expected2 MiB | 2.41 MiB/s  
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

In the context of F-Droid this will trigger protections https://git-scm.com/docs/git-fsck

Why is the repo problematic? Why do we need `no-checkout`? why is the index invalid?

**Comment by thekyber** [comment]
> Why is the repo problematic? Why do we need `no-checkout`? why is the index invalid?

I really don't know, try to delete it before cloning again.
I got this using the command I gave you:
```
Cloning into 'Tubular'...
remote: Enumerating objects: 133599, done.
remote: Counting objects: 100% (4032/4032), done.
remote: Compressing objects: 100% (1342/1342), done.
remote: Total 133599 (delta 2035), reused 3923 (delta 1973), pack-reused 129567
Receiving objects: 100% (133599/133599), 113.33 MiB | 1.37 MiB/s, done.
Resolving deltas: 100% (80785/80785), done.
```
