### ISSUE TITLE
Trying to add external downloading link on YouTube Revanced

### ISSUE THREAD

**Issue by eelalzep** [polymorphicshade/Tubular#61]
Like in [newpipe](org.schabi.newpipe), how can i do that in tabular.

**Comment by polymorphicshade** [comment]
I'm not familiar with the ReVanced integration with NewPipe, so I cannot help you.
Your best bet would be to consult Google and r/revancedapp on Reddit.

**Comment by eelalzep** [comment]
Thank a lot!!!
