### ISSUE TITLE
Whitelist channel switches off after changing from current video

### ISSUE THREAD

**Issue by disconnectreality** [polymorphicshade/Tubular#74]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/Tubular/releases/latest).
- [X] I am *not* able to reproduce the bug with the *latest version* of [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1. Select any video
2. Go to SponsorBlock tab and switch on "Whitelist channel"
3. Select another video by same channel or re-select the same video
4. Whitelist channel has been switched off and segments will be skipped again

### Expected behavior

Whitelist channel to persist on different videos from the same channel.

### Actual behavior

Appears to work only on the currently loaded video.

### Screenshots/Recordings

[Screencast.webm](https://github.com/polymorphicshade/Tubular/assets/38639821/330042ca-61b8-4c25-9981-ae7d3afc8a10) replicating issue on Android 11 / WayDroid 

### Affected Android/Custom ROM version

Android 14

### Affected device model

Samsung Galaxy S22 Ultra

**Comment by disconnectreality** [comment]
My mistake, I saw in the releases tab changelog that this was expected.

**Comment by polymorphicshade** [comment]
Haha.. I'm eagerly waiting for a block of free time I can dedicate to resuming this stuff 😔

**Comment by 532910** [comment]
please keep this open until fixed

**Comment by keks24** [comment]
> My mistake, I saw in the releases tab changelog that this was expected.

You mean the release of version [v0.27.0](https://github.com/polymorphicshade/Tubular/releases?q=whitelist&expanded=true)?

I was also expecting, that this option will persist.
