### ISSUE TITLE
[Question] Would you mind joining with some fork?

### ISSUE THREAD

**Issue by stdedos** [polymorphicshade/Tubular#75]
I am trying to see "what is the difference" between:

- https://github.com/TeamNewPipe/NewPipe
- https://github.com/polymorphicshade/NewPipe
- https://github.com/NewPipeX/NewPipeX

Would you mind joining your fork to the "most relevant" project? :confused: 

(by join, I mean: "connect the repositories in GitHub". Not to be confused with "joining efforts", etc)

-----

I don't mean any disrespect to your efforts (as I have been very happily using them for years), but would it improve "things" for everyone if there was a joined effort in _one_ project?

... Okay, maybe two - since https://github.com/TeamNewPipe disagrees with Sponsorblock :upside_down_face:

**Comment by polymorphicshade** [comment]
I'm happy to review and accept any pull requests with changes from those forks.

I will not spend time going through every fork and combining fixes/features together.

**Comment by stdedos** [comment]
I meant the opposite of https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork (GH support can do it, if you say from which fork does this repo come from)

**Comment by polymorphicshade** [comment]
Oh I think I see what you mean now.

No - I want my fork to derive directly from vanilla NewPipe, not any other forks. I don't this fork to be a derivation of a derivation, otherwise the time between releases will increase.

**Comment by stdedos** [comment]
Okay - so, what I hear is that https://github.com/polymorphicshade/Tubular is https://github.com/TeamNewPipe/NewPipe, without any https://github.com/polymorphicshade/NewPipe commits 

Thank you for clearing that out 🙏
