### ISSUE TITLE
Different icon

### ISSUE THREAD

**Issue by Toiletmason** [polymorphicshade/Tubular#9]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Seems like you've decided on it already, but any chance of a change? The new one is that great, but I know we can't go back to the old one. Maybe we could keep the color scheme and flip and reverse the cold Carbon Rom icon so it looks like a tubular ocean wave or something? Idk. Thanks for this fork regardless Polymorphicshade.

### Why do you want this feature?

New icon is lamesauce.

**Comment by polymorphicshade** [comment]
No, but you can always fork the code yourself and use your own icon 😉
